### ISSUE TITLE
Server http://localhost:3978/api/messages not start

### ISSUE THREAD

**Issue by pierlag** [NGRP/node-red-viseo-bot#1]
My config file : 
"server": {
        "port": 3978,
        "certificate":  {
            "crt": "C:\\Users\\pierlag\\Documents\\GitHub\\AscendBot\\data\\certificate\\server.crt",
            "key": "C:\\Users\\pierlag\\Documents\\GitHub\\AscendBot\\data\\certificate\\server.key"
        },
        "host": "http://localhost"
    },

But nothing response on 3978 via a navigator or via BotFramework

**Comment by JpEncausse** [comment]
It's http://localhost:3978/api/v1/messages (there is v1 added to the URL)

**Comment by JpEncausse** [comment]
I close the issue, tell me if you still have errors
